platform :ios, '6.0'
target 'KZPropertyMapper', :exclusive => true do
  pod 'NSLogger-CocoaLumberjack-connector'
  pod 'TestFlightSDK'
end
target 'KZPropertyMapperTests', :exclusive => true do
  pod 'Kiwi'
end
